services:
  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        MODE: development
    ports:
    - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://rye:admin@db:5432/horyezon?schema=public"
    volumes:
      - ../:/app
    container_name: next-prisma-dev
    command: yarn dev

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: rye
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: horyezon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
